name: CI

on:
  push:
    tags: v*
  pull_request:
    branches: "*"

jobs:
  all:
    name: all
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run lint
      # jhurliman: disable testing in CI for now, it needs special handling with xvfb
      # - run: yarn run test

      - name: Publish to NPM
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: yarn npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
